server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swaggertp
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    ma.geo.local: INFO


springdoc:
    swagger-ui:
      use-root-path: true
      path: /swagger-ui.html
      disable-swagger-default-url: true
